version: '3'
services:
    postgres:
        restart: always      
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

        volumes:
            - /home/ops/docker-airflow_db:/var/lib/postgresql/data

    webserver:
        image: nwrc-airflow
        user: root
        restart: always
        depends_on:
            - postgres
        env_file:
            - nwrc.local.env
        volumes:
            # airflow
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
            - ./config/airflow.cfg:/urs/local/airflow/airflow.cfg
            - ./config/docker-airflow_CoreConfig.ini:/usr/local/config/docker-airflow_CoreConfig.ini

            # data
            - /data/albedo/:/data/albedo
            - /data/snowpack/forecasts/hrrr:/data/snowpack/forecasts/hrrr
            - /home/ops/backups/basin_ops:/data/backups
            - /home/ops:/home/ops

            # mount docker socket for awsm and katana
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /usr/bin/docker:/bin/docker:ro

            # ssh
            - /home/ops/.ssh:/root/.ssh
            - /home/ops/.ssh/.gitconfig:/root/.gitconfig

        ports:
            - "32778:8080"
            - "443:443"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
